### ISSUE TITLE
`import fancy_gym` not working after `pip install .`

### ISSUE THREAD

**Issue by maxmunzel** [ALRhub/fancy_gym#82]
The default target does not install `mujoco`, but still imports it. The solution is either to add `mujoco` to the standard dependencies or handle its absence softly.

Reproduction:

``` bash
casparfriedrich@littlebird /tmp> conda create -n test python=3.8                                                     
# ...
casparfriedrich@littlebird /tmp> git clone git@github.com:ALRhub/fancy_gym.git                                        
casparfriedrich@littlebird /tmp> cd fancy_gym/                                                                        
casparfriedrich@littlebird /t/fancy_gym (master)> conda activate test                                                 
casparfriedrich@littlebird /t/fancy_gym (master)> pip3 install .                                                      
# ...
casparfriedrich@littlebird /t/fancy_gym (master)> python3 -c "import fancy_gym"                                       (test)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/fancy_gym/fancy_gym/__init__.py", line 1, in <module>
    from fancy_gym import dmc, meta, open_ai
  File "/private/tmp/fancy_gym/fancy_gym/dmc/__init__.py", line 6, in <module>
    from ..envs.registry import register
  File "/private/tmp/fancy_gym/fancy_gym/envs/__init__.py", line 7, in <module>
    from . import classic_control, mujoco
  File "/private/tmp/fancy_gym/fancy_gym/envs/mujoco/__init__.py", line 2, in <module>
    from .beerpong.beerpong import BeerPongEnv, BeerPongEnvStepBasedEpisodicReward
  File "/private/tmp/fancy_gym/fancy_gym/envs/mujoco/beerpong/beerpong.py", line 10, in <module>
    import mujoco
ModuleNotFoundError: No module named 'mujoco'

**Comment by D-o-d-o-x** [comment]
Is now fixed on master (via PR #84).
